server:
    port: 8080

logging:
    level:
        root: INFO
        org.springframework.web: INFO
        org.springframework.security: INFO
        org.springframework.security.oauth2: INFO

spring:
    security:
        oauth2:
            client:
                registration:
                    trigger-client-oidc:
                        provider: spring
                        client-id: trigger-client
                        client-secret: kWQ7Vyvw6U1G6lIb8M2Q5Fv9hN4X7cDz
                        authorization-grant-type: authorization_code
                        redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
                        scope: openid
                        client-name: trigger-client-oidc
                    trigger-client-authorization-code:
                        provider: spring
                        client-id: trigger-client
                        client-secret: kWQ7Vyvw6U1G6lIb8M2Q5Fv9hN4X7cDz
                        authorization-grant-type: authorization_code
                        redirect-uri: "http://127.0.0.1:8080/authorized"
                        scope: trigger.read
                        client-name: trigger-client-authorization-code
                provider:
                    spring:
                        issuer-uri: http://auth-server:9000